export let Resources = {
  successRegister: "Successfully registered.",
  successUpdated: "Successfully updated.",
  savedSuccessfully: "The changes were saved successfully.",
  passChangedSuccess: "The password was changed successfully.",
  mailSent: "The mail was sent successfully.",
  passRessSuccess: "Your password were successfully reset.",
  successDelete: "Successfully deleted.",
  successChange: "The change was added successfully.",
  mailError: "The mail can't be sent.",
  loginToAccess: "First, you must logout to access login form.",
  invalidCredentials: "Invalid username or password.",
  oops: "Oops! Something went wrong.",
  sessionExpired: "Your session was expired. Please, log in again.",
  unauthorized: 'Unauthorized!',
}
